<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'feature_flags' => [
            'tx_deskmaadmin_site' => [
                'enableNewUserTable' => false,
            ],
        ],
        'installToolPassword' => '$P$C9IKjSFzHKNoHxmX3Q73Z/V1AIaxKp0',
        'loginSecurityLevel' => 'rsa',
        'versionNumberInFilename' => '0',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => 'test',
                'driver' => 'mysqli',
                'host' => 'localhost',
                'password' => '',
                'unix_socket' => '',
                'user' => 'deskma',
            ],
        ],
    ],
    'EXT' => [
        'allowGlobalInstall' => true,
        'extConf' => [
            'backend' => 'a:5:{s:9:"loginLogo";s:68:"typo3/ext/deskma_provider/Resources/Public/Images/Backend/deskma.png";s:19:"loginHighlightColor";s:7:"#3366bb";s:20:"loginBackgroundImage";s:92:"typo3/ext/deskma_provider/Resources/Public/Images/Backend/deskmabackgroundtypo3login2400.jpg";s:11:"backendLogo";s:0:"";s:14:"backendFavicon";s:69:"typo3/ext/deskma_provider/Resources/Public/Images/Backend/favicon.ico";}',
            'bootstrap_package' => 'a:7:{s:16:"disablePageTsRTE";s:1:"0";s:27:"disablePageTsBackendLayouts";s:1:"0";s:20:"disablePageTsTCEMAIN";s:1:"0";s:20:"disablePageTsTCEFORM";s:1:"0";s:30:"disablePageTsTtContentPreviews";s:1:"0";s:36:"disablePageTsNewContentElementWizard";s:1:"0";s:21:"disableLessProcessing";s:1:"0";}',
            'compatibility6' => 'a:1:{s:15:"setPageTSconfig";s:1:"1";}',
            'cs_seo' => 'a:12:{s:17:"enablePathSegment";s:1:"1";s:15:"realURLAutoConf";s:1:"1";s:11:"tsConfigPid";s:1:"1";s:8:"maxTitle";s:2:"57";s:14:"maxDescription";s:3:"156";s:11:"maxNavTitle";s:2:"50";s:12:"inPageModule";s:1:"0";s:18:"evaluationDoktypes";s:1:"1";s:10:"evaluators";s:38:"Title,Description,H1,H2,Images,Keyword";s:8:"minTitle";s:2:"40";s:14:"minDescription";s:3:"140";s:5:"maxH2";s:1:"6";}',
            'deskma_admin' => 'a:3:{s:14:"datetimeFormat";s:14:"jS F Y g:i:s A";s:12:"cachebackend";s:5:"mysql";s:9:"translate";s:2:"no";}',
            'deskma_adwords' => 'a:0:{}',
            'deskma_attachments' => 'a:0:{}',
            'deskma_autosignon' => 'a:0:{}',
            'deskma_billy' => 'a:0:{}',
            'deskma_customers' => 'a:0:{}',
            'deskma_dinero' => 'a:0:{}',
            'deskma_extrafields' => 'a:0:{}',
            'deskma_fastaccess' => 'a:0:{}',
            'deskma_fe' => 'a:0:{}',
            'deskma_provider' => 'a:0:{}',
            'deskma_subscriptions' => 'a:0:{}',
            'deskma_webpush' => 'a:0:{}',
            'deskma_webservices' => 'a:0:{}',
            'deskma_workqueue' => 'a:0:{}',
            'direct_mail' => 'a:9:{s:12:"sendPerCycle";s:2:"50";s:13:"cron_language";s:2:"da";s:14:"addRecipFields";s:0:"";s:10:"adminEmail";s:13:"info@t3cms.dk";s:7:"cronInt";s:1:"5";s:15:"notificationJob";s:1:"1";s:19:"enablePlainTextNews";s:1:"1";s:14:"UseHttpToFetch";s:1:"0";s:13:"updateMessage";s:1:"0";}',
            'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
            'fluid_styled_content' => 'a:1:{s:32:"loadContentElementWizardTsConfig";s:1:"1";}',
            'fluidcontent' => 'a:0:{}',
            'fluidpages' => 'a:3:{s:8:"autoload";s:1:"0";s:8:"doktypes";s:0:"";s:33:"pagesLanguageConfigurationOverlay";s:1:"0";}',
            'flux' => 'a:4:{s:9:"debugMode";s:1:"0";s:7:"compact";s:1:"0";s:17:"listNestedContent";s:1:"0";s:12:"handleErrors";s:1:"0";}',
            'gridelements' => 'a:2:{s:20:"additionalStylesheet";s:0:"";s:19:"nestingInListModule";s:1:"0";}',
            'introduction' => 'a:0:{}',
            'jh_magnificpopup' => 'a:2:{s:19:"colPosOfIrreContent";s:3:"109";s:19:"enableAlphaFeatures";s:1:"0";}',
            'jumpurl' => 'a:0:{}',
            'lfeditor' => 'a:4:{s:13:"viewLanguages";s:2:"da";s:15:"defaultLanguage";s:2:"en";s:9:"extIgnore";s:23:"/^(CVS|.svn|.git|csh_)/";s:13:"changeXlfDate";s:1:"1";}',
            'linkvalidator' => 'a:0:{}',
            'mediace' => 'a:0:{}',
            'news' => 'a:20:{s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:1:"1";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"1";s:21:"contentElementPreview";s:1:"1";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:4:"none";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:19:"dateTimeNotRequired";s:1:"0";s:11:"archiveDate";s:4:"date";s:24:"showAdministrationModule";s:1:"1";s:35:"hidePageTreeForAdministrationModule";s:1:"0";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";s:29:"removeListActionFromFlexforms";s:1:"2";s:20:"pageModuleFieldsNews";s:317:"LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_simple=title,datetime;LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_advanced=title,datetime,teaser,categories;LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_complex=title,datetime,teaser,categories,archive;";s:24:"pageModuleFieldsCategory";s:17:"title,description";s:25:"showMediaDescriptionField";s:1:"0";s:6:"useFal";s:1:"1";}',
            'pdfviewhelpers' => 'a:0:{}',
            'perfectlightbox' => 'a:0:{}',
            'phpmyadmin' => 'a:4:{s:12:"hideOtherDBs";s:1:"1";s:9:"uploadDir";s:21:"uploads/tx_phpmyadmin";s:10:"allowedIps";s:26:"89.150.178.16,2.110.21.191";s:12:"useDevIpMask";s:1:"0";}',
            'realurl' => 'a:4:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";}',
            'recycler' => 'a:0:{}',
            'rest' => 'a:2:{s:11:"logRequests";s:1:"0";s:11:"logResponse";s:1:"0";}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'rte_ckeditor' => 'a:0:{}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
            'seeder' => 'a:2:{s:11:"pathToFaker";s:24:"vendor/fzaninotto/faker/";s:6:"locale";s:5:"en_US";}',
            'sentry_client' => 'a:2:{s:3:"dsn";s:0:"";s:14:"productionOnly";s:1:"1";}',
            'seo_basics' => 'a:1:{s:10:"xmlSitemap";s:1:"1";}',
            'sys_action' => 'a:0:{}',
            't3adminer' => 'a:3:{s:8:"IPaccess";s:13:"89.150.178.16";s:14:"applyDevIpMask";s:1:"0";s:15:"exportDirectory";s:9:"fileadmin";}',
            't3cmsprovider' => 'a:0:{}',
            'taskcenter' => 'a:0:{}',
            'tt_address' => 'a:3:{s:21:"backwardsCompatFormat";s:9:"%1$s %3$s";s:24:"storeBackwardsCompatName";s:1:"1";s:17:"readOnlyNameField";s:1:"1";}',
            'typo3profiler' => 'a:7:{s:7:"enabled";s:1:"1";s:12:"includeTypes";s:6:"SELECT";s:13:"excludeTables";s:167:"cache_%,tx_devlog,%session%,cachingframework_%,pages,tx_realurl%,tt_content,tx_templavoila%,sys_template,sys_domain,tx_extbase_cache_object,tx_extbase_cache_reflection";s:13:"excludeRegexp";s:23:"/(@@SESSION|@@VERSION)/";s:9:"nbQueries";s:1:"5";s:10:"maxQueries";s:3:"100";s:15:"debugbarenabled";s:1:"0";}',
            'vhs' => 'a:1:{s:20:"disableAssetHandling";s:1:"0";}',
            'yoast_seo' => 'a:0:{}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'da',
            ],
        ],
    ],
    'FE' => [
        'debug' => false,
        'loginSecurityLevel' => 'rsa',
    ],
    'GFX' => [
        'jpg_quality' => '80',
        'processor' => 'GraphicsMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'RGB',
        'processor_effects' => -1,
        'processor_enabled' => true,
        'processor_path' => '/usr/local/bin/',
        'processor_path_lzw' => '/usr/local/bin/',
    ],
    'MAIL' => [
        'transport' => 'smtp',
        'transport_sendmail_command' => '',
        'transport_smtp_encrypt' => 'ssl',
        'transport_smtp_password' => '[DQ!x23+Wu25pmK-',
        'transport_smtp_server' => 'smtp.gmail.com:465',
        'transport_smtp_username' => 'info@deskma.com',
    ],
    'SYS' => [
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\NullBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
            ],
        ],
        'devIPmask' => '',
        'displayErrors' => '1',
        'enableDeprecationLog' => false,
        'encryptionKey' => 'a801b8590744b043fd74c5037b8a3a8c938a19296ed99d03d62b3ae5022c27bcfd12d74623dc8661efc01f3ec3c762f9',
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => false,
        'phpTimeZone' => 'UTC',
        'sitename' => 'Model 8',
        'sqlDebug' => 0,
        'systemLog' => '',
        'systemLogLevel' => 2,
    ],
];
